project_id = "qiczzqaevdztzhllgnlg"

[functions.booking-notification]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.create-blog-post]
verify_jwt = true

[functions.generate-invoice-ai]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.setup-push]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.notify-blog-subscribers]
verify_jwt = false

[functions.send-pdf-email]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.vapi-booking-webhook]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.send-admin-email]
verify_jwt = true

[functions.receive-email-webhook]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.send-messenger-message]
verify_jwt = true

[functions.send-instagram-message]
verify_jwt = true

[functions.telegram-wallet-bot]
verify_jwt = false

[functions.post-to-social]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.telegram-setup]
verify_jwt = true

[functions.generate-og-image]
verify_jwt = true

[functions.generate-all-og-images]
verify_jwt = true

[functions.og-meta]
verify_jwt = false
