project_id = "qiczzqaevdztzhllgnlg"

[functions.booking-notification]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.create-blog-post]
verify_jwt = true

[functions.generate-invoice-ai]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.setup-push]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.notify-blog-subscribers]
verify_jwt = false

[functions.send-pdf-email]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.vapi-booking-webhook]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.send-admin-email]
verify_jwt = true
