project_id = "qiczzqaevdztzhllgnlg"

[functions.booking-notification]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.create-blog-post]
verify_jwt = true

[functions.generate-invoice-ai]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true